version: '3.3'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: nginx
    ports:
      - 80:80
    links:
      - fpm
    volumes:
      - .:/var/www/laravel-docker
  fpm:
    build:
      context: .
      dockerfile: docker/fpm/Dockerfile
    volumes:
      - .:/var/www/laravel-docker
      - ./docker/fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    links:
      - mysql
    environment:
      - XDEBUG_SESSION=docker-server
  mysql:
    container_name: dbs
    image: mariadb:10.3
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
  redis:
    image: redis
    ports:
      - 6379:6379