FROM php:8.0-fpm

RUN docker-php-ext-install mysqli pdo pdo_mysql
#    && pecl install xdebug \
#    && docker-php-ext-enable xdebug pdo_mysql
WORKDIR /var/www/laravel-docker
# Куда же без composer'а.
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


